# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: MyEvenProject
    - name: Build
      run: dotnet build
      working-directory: MyEvenProject
    - name: Test
      run: dotnet test
      working-directory: MyEvenProject.tests
    - name: Restore dependencies
      run: dotnet restore
      working-directory: MyEvenProject.tests
